
weatherService:
  apikey: "47643c77aa63860e1dede6826a18c7e2"
  baseUrl: "http://api.openweathermap.org/data/2.5/weather"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weathersnapshot
    username: nico
    password: leta
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
pring:
  jackson:
    date-format: YYYY-MM-DD
